apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-dev
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/diliev97/deployment-repo
        revision: master
        directories:
          - path: apps/*/base
  template:
    metadata:
      name: "{{path[1]}}-dev"
      labels:
        app: "{{path[1]}}"
        env: dev
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd-image-updater.argoproj.io/image-list: "image=ghcr.io/diliev97/{{path[1]}}"
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/helm.write-back-target: "../overlays/dev/values.yaml"
        argocd-image-updater.argoproj.io/git-branch: master
        argocd-image-updater.argoproj.io/image-update-strategy: latest
        notifications.argoproj.io/on-image-update: "ms-teams"
        notifications.argoproj.io/on-sync-failed: "ms-teams"
        notifications.argoproj.io/on-sync-succeeded: "ms-teams"
        notifications.argoproj.io/on-health-degraded: "ms-teams"
        notifications.argoproj.io/on-health-healthy: "ms-teams"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/diliev97/deployment-repo
          targetRevision: master
          path: "apps/{{path[1]}}/base"
          helm:
            valueFiles:
              - "../overlays/dev/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m