apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-dev
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/diliev97/deployment-repo
        revision: master
        directories:
          - path: apps/*/base
  template:
    metadata:
      name: "{{path[1]}}"
      labels:
        app: "{{path[1]}}"
        env: dev
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://github.com/diliev97/deployment-repo
          targetRevision: master
          path: "apps/{{path[1]}}/base"
          helm:
            valueFiles:
              - "apps/{{path[1]}}/overlays/dev/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[1]}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m