replicaCount: 1

image:
  tag: "dev"

podAnnotations:
  argocd-image-updater.argoproj.io/image-list: image=ghcr.io/diliev97/simple-app-2:*-dev
  argocd-image-updater.argoproj.io/write-back-method: git
  argocd-image-updater.argoproj.io/git-branch: master

service:
  type: NodePort
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

#nodeSelector:
#  environment: dev

ingress:
  enabled: false