keycloak:
  instances: 1
  hostname: dev-bnxg.dsk.az
  tlsSecret: dev-bnxg.dsk.az

  db:
    vendor: mssql
    url: "jdbc:sqlserver://bnxg-dev-weu.4ed034e4d4bc.database.windows.net:1433;database=keycloak;"
    secretName: keycloak-db-secret-dev
    usernameKey: username
    passwordKey: password

  probes:
    managementPort: 9000
    scheme: HTTPS
    startupPath: /auth/health/started
    readinessPath: /auth/health/ready
    livenessPath: /auth/health/live

nameOverride: ""
fullnameOverride: "keycloak"

image:
  repository: crdsk13bnxgweu.azurecr.io/keycloak/keycloak-bnxg
  pullPolicy: Always

externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStoreName: aks18-bnxgdev-weu-keyvault
  targetSecretName: keycloak-db-secret-dev
  remote:
    usernameSecretName: bnxg-dev-weu-kc-username
    passwordSecretName: bnxg-dev-weu-kc-password

gateway:
  enabled: true
  class: traefik
  hostname: dev-bnxg.dsk.az
  httpPort: 8000
  httpsPort: 8443
  tlsSecretName: dev-bnxg.dsk.az
  tlsSecretNamespace: dev

httproute:
  name: keycloak
  enabled: false
  pathPrefix: /auth
  serviceName: keycloak-service
  servicePort: 8443

nodeSelector: {}