keycloak:
  instances: 1
  http:
    httpEnabled: true

  db:
    vendor: mssql
    usernameKey: username
    passwordKey: password

  probes:
    managementPort: 9000
    scheme: HTTPS
    startupPath: /auth/health/started
    readinessPath: /auth/health/ready
    livenessPath: /auth/health/live

nameOverride: ""
fullnameOverride: "keycloak"

image:
  repository: crdsk13bnxgweu.azurecr.io/keycloak/keycloak-bnxg
  pullPolicy: Always

externalSecrets:
  enabled: true
  refreshInterval: 1h
  targetSecretName: keycloak-db-secret

gateway:
  class: traefik
  httpPort: 8000
  httpsPort: 8443

httproute:
  name: keycloak
  enabled: false
  pathPrefix: /auth
  serviceName: keycloak
  servicePort: 8443

tlsroute:
  enabled: false
  name: keycloak-tlsroute
  parentListenerName: tls
  backend:
    serviceName: keycloak
    servicePort: 8443

backendTlsPolicy:
  enabled: false
  name: keycloak-tls-policy
  targetServiceName: keycloak
  caConfigMapName: ca.crt

nodeSelector: {}