apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keycloak-secret-provider-class-dev
  namespace: keycloak
spec:
  provider: azure
  secretObjects:
  - secretName: keycloak-db-secret-dev
    type: Opaque
    data:
    - objectName: bnxg-dev-weu-kc-username
      key: username
    - objectName: bnxg-dev-weu-kc-password
      key: password
  parameters:
    tenantId: 07ffa628-8eb8-4bc5-8695-aab938c302dd
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: eaf274ef-654a-47d2-a904-a217e3bfc791
    keyvaultName: AKS18-BNXGDev-weu
    objects:  |
      array:
        - |
          objectName: "bnxg-dev-weu-kc-username"
          objectType: secret
        - |
          objectName: "bnxg-dev-weu-kc-password"
          objectType: secret