{{- if .Values.backendTlsPolicy.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ .Values.backendTlsPolicy.name }}
  namespace: {{ .Values.namespace }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: {{ .Values.backendTlsPolicy.targetServiceName }}
  validation:
    hostname: {{ .Values.backendTlsPolicy.validationHostname | quote }}
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: {{ .Values.backendTlsPolicy.caConfigMapName }}
{{- end }}