{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.ssbSecretName }}
  labels:
    {{- include "integration-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.ssbSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: ssb-client-id
      remoteRef:
        key: {{ .Release.Namespace }}-integration-service-client-id
    - secretKey: ssb-client-secret
      remoteRef:
        key: {{ .Release.Namespace }}-integration-service-client-secret
    - secretKey: ssb-username
      remoteRef:
        key: {{ .Release.Namespace }}-integration-service-username
    - secretKey: ssb-password
      remoteRef:
        key: {{ .Release.Namespace }}-integration-service-password
{{- end }}